name: Daily Auto Commit

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST (India time)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last updated: $(date)" >> activity.txt

      - name: Commit and Push
        run: |
          git config user.name "mehul-makvana"
          git config user.email "mehulmakavana52@gmail.com"
          git add .
          git commit -m "Daily auto update $(date)" || echo "No changes"
          git push
